const ROLES = {
  ANALISTA_MASTER: 'ANALISTA_MASTER',
  ANALISTA_TESTADOR: 'ANALISTA_TESTADOR',
  GERENTE: 'GERENTE',
  COORDENADOR: 'COORDENADOR',
  SUPERINTENDENTE: 'SUPERINTENDENTE',
  DIRETOR: 'DIRETOR',
  SUPERVISOR: 'SUPERVISOR',
  ANALISTA: 'ANALISTA',
  ESTAGIARIO: 'ESTAGIARIO',
}

const TI_AREA = 'Tecnologia da Informação'

const TI_ROLES = [ROLES.ANALISTA_MASTER, ROLES.ANALISTA_TESTADOR]
const MANAGER_ROLES = [ROLES.GERENTE, ROLES.COORDENADOR]
const TI_MANAGERS = [...TI_ROLES, ...MANAGER_ROLES]
const PRIVILEGED_ROLES = [...TI_MANAGERS, ROLES.SUPERINTENDENTE, ROLES.DIRETOR]

const PHASES = {
  BACKLOG: 'BACKLOG',
  RECEBIDA: 'RECEBIDA',
  ENTREVISTA_SOLICITANTE: 'ENTREVISTA_SOLICITANTE',
  LEVANTAMENTO_REQUISITOS: 'LEVANTAMENTO_REQUISITOS',
  ANALISE_SOLUCAO: 'ANALISE_SOLUCAO',
  DESENVOLVIMENTO: 'DESENVOLVIMENTO',
  TESTES: 'TESTES',
  VALIDACAO_SOLICITANTE: 'VALIDACAO_SOLICITANTE',
  ENTREGUE: 'ENTREGUE',
  SUPORTE: 'SUPORTE',
}

const ORIGINS = {
  NORMAL: 'NORMAL',
  FRESHSERVICE: 'FRESHSERVICE',
}

const TRAFFIC_LIGHTS = {
  VERDE: 'VERDE',
  AMARELO: 'AMARELO',
  VERMELHO: 'VERMELHO',
}

module.exports = { ROLES, TI_AREA, TI_ROLES, MANAGER_ROLES, TI_MANAGERS, PRIVILEGED_ROLES, PHASES, ORIGINS, TRAFFIC_LIGHTS }